name: WakaTime Readme

on:
  schedule:
    - cron: "0 0 * * *"   # todo dia 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update README with WakaTime stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Ãºltimos 7 dias (substitui TIME_RANGE)
          WAKATIME_API_URL: "https://wakatime.com/api/v1/users/current/stats/last_7_days"

          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_OS: true
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_UPDATED_DATE: true
          SHOW_SHORT_INFO: true

          COMMIT_MESSAGE: "Update WakaTime stats"
